"""Assemble the weekly candidate pool for one edition.

This is the coverage floor only. It fetches structured feeds, tags + de-dupes,
and writes two files into data/editions/<start>/:

  candidates.json  — the de-duped, family-filtered candidate pool + weather
  research.md      — a scaffold the ccc-research skill fills in via DISCOVERY
                     (hunt the non-obvious) and CURATION (score, cut, rank).

The Python stops at "here are clean candidates." Turning that into a curated
research.json — the part that needs taste — is the skill's job. See
.claude/skills/ccc-research/SKILL.md.

    uv run python scripts/build_edition.py --start 2026-07-16 --days 7
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import fetch_ics
import fetch_weather
from ccc_core import DATA, dedupe, parse_window


def build(start: str | None, days: int, min_relevance: int = 1) -> dict:
    d0, d1 = parse_window(start, days)

    raw_events, report = fetch_ics.fetch_all(d0, d1)
    deduped = dedupe(raw_events)

    # Coverage filter: drop obvious non-family + obvious non-events from the
    # pool. Anything borderline stays IN with a flag — the skill decides, not us.
    def keep(ev) -> bool:
        if "likely_non_event" in ev.auto_flags:
            return False
        return ev.family_relevance >= min_relevance

    kept = [e for e in deduped if keep(e)]
    dropped = [e for e in deduped if not keep(e)]

    try:
        weather = fetch_weather.fetch_forecast(periods=days * 2)
    except Exception as exc:  # noqa: BLE001
        weather = {"error": str(exc)[:200]}

    return {
        "edition": {"start": d0.isoformat(), "end": d1.isoformat(), "days": days},
        "coverage_report": report,
        "counts": {
            "raw": len(raw_events),
            "after_dedupe": len(deduped),
            "kept_candidates": len(kept),
            "dropped": len(dropped),
        },
        "weather": weather,
        "candidates": [e.to_dict() for e in kept],
        "dropped_for_review": [
            {"title": e.title, "start": e.start, "source": e.source, "flags": e.auto_flags}
            for e in dropped
        ],
    }


RESEARCH_SCAFFOLD = """# Research scaffold — edition {start} → {end}

Generated by build_edition.py (coverage floor). The Python found **{kept} candidates**
from structured feeds. That's the floor, not the edition. Now do the two jobs that
need taste:

## 1. DISCOVERY — hunt the non-obvious (this is why people subscribe)
The candidate pool below is calendars only. Go find what ISN'T on a calendar:
- [ ] Web-search local Instagram/Facebook for pop-ups, new openings, one-off social
      occasions this week (breweries w/ family hours, coffee shops, farms, maker spaces).
- [ ] Skim r/IowaCity and local parent Facebook groups for word-of-mouth happenings.
- [ ] Check Little Village *editorial* picks (not just their calendar).
- [ ] Note any new business opening / seasonal first (first pumpkin patch weekend, etc.).
- [ ] Reader tips, if any.
Aim for **at least 2-3 finds that were not on any calendar.** One surprising find beats
twenty calendar rows.

## 2. CURATION — score, cut, rank (the newsletter has a POV)
For every candidate + discovery, judge: *would a busy parent actually care?*
- Cut filler, duplicates, and anything with `likely_non_event` / `age_uncertain` you
  can't resolve.
- Assign each keeper an `interest_score` (1-5) and a section (Week Ahead / Free & Cheap
  Five / School Notes / Deep Dive / Bulletin).
- Fix the coarse auto-tags (age bands, cost, town) — trust your read over the heuristic.
- Write a one-line **hook** per event: why it's worth it, in the house voice.
- Pick ONE Deep Dive idea for the week.

Write the result to `research.json` (see SKILL.md for the shape). candidates.json is your
raw material; research.json is the curated edition input.

---
Coverage counts: {counts}
Dropped as junk/non-family (peek in candidates.json → dropped_for_review): {dropped}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the weekly candidate pool.")
    ap.add_argument("--start", help="YYYY-MM-DD (default: today)")
    ap.add_argument("--days", type=int, default=7)
    ap.add_argument("--min-relevance", type=int, default=1)
    ap.add_argument("--outdir", help="override output dir")
    args = ap.parse_args()

    result = build(args.start, args.days, args.min_relevance)
    start = result["edition"]["start"]

    outdir = Path(args.outdir) if args.outdir else (DATA / "editions" / start)
    outdir.mkdir(parents=True, exist_ok=True)

    (outdir / "candidates.json").write_text(json.dumps(result, indent=2))
    (outdir / "research.md").write_text(RESEARCH_SCAFFOLD.format(
        start=result["edition"]["start"],
        end=result["edition"]["end"],
        kept=result["counts"]["kept_candidates"],
        counts=result["counts"],
        dropped=result["counts"]["dropped"],
    ))

    print(f"Wrote {outdir}/candidates.json  ({result['counts']['kept_candidates']} candidates)")
    print(f"Wrote {outdir}/research.md      (discovery + curation scaffold)")
    print(f"Coverage report: {result['coverage_report']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
