"""Assemble the weekly candidate pool for one edition.

This is the coverage floor only. It fetches structured feeds, tags + de-dupes,
and writes two files into data/editions/<start>/:

  candidates.json  — the de-duped, family-filtered candidate pool + weather
  research.md      — a scaffold the ccc-research skill fills in via DISCOVERY
                     (hunt the non-obvious) and CURATION (score, cut, rank).

The Python stops at "here are clean candidates." Turning that into a curated
research.json — the part that needs taste — is the skill's job. See
.claude/skills/ccc-research/SKILL.md.

    uv run python scripts/build_edition.py --start 2026-07-16 --days 7
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import fetch_facebook
import fetch_html
import fetch_ics
import fetch_instagram
import fetch_weather
from ccc_core import DATA, dedupe, parse_window


def build(start: str | None, days: int, min_relevance: int = 1, discover: bool = False) -> dict:
    d0, d1 = parse_window(start, days)

    # Free coverage floor: ICS feeds + HTML/API sources (Localist, JSON-LD).
    ics_events, ics_report = fetch_ics.fetch_all(d0, d1)
    html_events, html_report = fetch_html.fetch_all(d0, d1)
    report = ics_report + html_report
    raw_events = ics_events + html_events

    # Paid discovery (opt-in, uses Scrape Creators credits): structured Facebook
    # events merge into the pool; Instagram returns caption signals for the skill.
    fb_report: list[dict] = []
    ig_signals: dict = {}
    if discover:
        try:
            fb = fetch_facebook.fetch_all(d0, d1, max_calls=None)
            raw_events += [_dict_to_event(e) for e in fb["events"]]
            fb_report = fb["report"]
        except Exception as exc:  # noqa: BLE001
            fb_report = [{"status": "error", "error": str(exc)[:160]}]
        try:
            ig_signals = fetch_instagram.fetch_all(days=max(days, 21), max_handles=None)
        except Exception as exc:  # noqa: BLE001
            ig_signals = {"error": str(exc)[:160]}

    deduped = dedupe(raw_events)

    # Coverage filter: drop only genuine junk. Community events (festivals,
    # markets, park concerts) often don't trip the kid-keyword heuristic but are
    # exactly what a family newsletter wants, so DO NOT drop on family_relevance.
    # Borderline stays IN with a flag — the curation skill decides, not this filter.
    def keep(ev) -> bool:
        if "likely_non_event" in ev.auto_flags:
            return False
        # clearly adults-only (21+ / bar shows) with zero family signal
        if any(f.startswith("adult_signal") for f in ev.auto_flags) and ev.family_relevance == 0:
            return False
        return True

    kept = [e for e in deduped if keep(e)]
    dropped = [e for e in deduped if not keep(e)]

    try:
        weather = fetch_weather.fetch_forecast(periods=days * 2)
    except Exception as exc:  # noqa: BLE001
        weather = {"error": str(exc)[:200]}

    return {
        "edition": {"start": d0.isoformat(), "end": d1.isoformat(), "days": days},
        "coverage_report": report,
        "facebook_report": fb_report,
        "counts": {
            "raw": len(raw_events),
            "after_dedupe": len(deduped),
            "kept_candidates": len(kept),
            "dropped": len(dropped),
        },
        "weather": weather,
        "candidates": [e.to_dict() for e in kept],
        "dropped_for_review": [
            {"title": e.title, "start": e.start, "source": e.source, "flags": e.auto_flags}
            for e in dropped
        ],
        "instagram_signals": ig_signals,
    }


def _dict_to_event(d: dict):
    """Rebuild an Event from a fetch_facebook dict so it can be deduped."""
    from dataclasses import fields

    from ccc_core import Event

    allowed = {f.name for f in fields(Event)}
    return Event(**{k: v for k, v in d.items() if k in allowed})


RESEARCH_SCAFFOLD = """# Research scaffold — edition {start} → {end}

Generated by build_edition.py (coverage floor). The Python found **{kept} candidates**
from structured feeds. That's the floor, not the edition. Now do the two jobs that
need taste:

## 1. DISCOVERY — hunt the non-obvious (this is why people subscribe)
The candidate pool below is calendars only. Go find what ISN'T on a calendar:
- [ ] Web-search local Instagram/Facebook for pop-ups, new openings, one-off social
      occasions this week (breweries w/ family hours, coffee shops, farms, maker spaces).
- [ ] Skim r/IowaCity and local parent Facebook groups for word-of-mouth happenings.
- [ ] Check Little Village *editorial* picks (not just their calendar).
- [ ] Note any new business opening / seasonal first (first pumpkin patch weekend, etc.).
- [ ] Reader tips, if any.
Aim for **at least 2-3 finds that were not on any calendar.** One surprising find beats
twenty calendar rows.

## 2. CURATION — score, cut, rank (the newsletter has a POV)
For every candidate + discovery, judge: *would a busy parent actually care?*
- Cut filler, duplicates, and anything with `likely_non_event` / `age_uncertain` you
  can't resolve.
- Assign each keeper an `interest_score` (1-5) and a section (Week Ahead / Free & Cheap
  Five / School Notes / Deep Dive / Bulletin).
- Fix the coarse auto-tags (age bands, cost, town) — trust your read over the heuristic.
- Write a one-line **hook** per event: why it's worth it, in the house voice.
- Pick ONE Deep Dive idea for the week.

Write the result to `research.json` (see SKILL.md for the shape). candidates.json is your
raw material; research.json is the curated edition input.

---
Coverage counts: {counts}
Dropped as junk/non-family (peek in candidates.json → dropped_for_review): {dropped}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the weekly candidate pool.")
    ap.add_argument("--start", help="YYYY-MM-DD (default: today)")
    ap.add_argument("--days", type=int, default=7)
    ap.add_argument("--min-relevance", type=int, default=1)
    ap.add_argument("--discover", action="store_true",
                    help="also pull Facebook events + Instagram signals (uses Scrape Creators credits)")
    ap.add_argument("--outdir", help="override output dir")
    args = ap.parse_args()

    result = build(args.start, args.days, args.min_relevance, discover=args.discover)
    start = result["edition"]["start"]

    outdir = Path(args.outdir) if args.outdir else (DATA / "editions" / start)
    outdir.mkdir(parents=True, exist_ok=True)

    (outdir / "candidates.json").write_text(json.dumps(result, indent=2))
    (outdir / "research.md").write_text(RESEARCH_SCAFFOLD.format(
        start=result["edition"]["start"],
        end=result["edition"]["end"],
        kept=result["counts"]["kept_candidates"],
        counts=result["counts"],
        dropped=result["counts"]["dropped"],
    ))

    print(f"Wrote {outdir}/candidates.json  ({result['counts']['kept_candidates']} candidates)")
    print(f"Wrote {outdir}/research.md      (discovery + curation scaffold)")
    print(f"Coverage report: {result['coverage_report']}")
    if args.discover:
        print(f"Facebook report: {result['facebook_report']}")
        ig = result.get("instagram_signals", {})
        print(f"Instagram: {ig.get('report', ig.get('error', 'n/a'))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
